server:
  port: 7230
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://cartoon-ali.com:3306/test
    username: test
    password: $Qwe13579
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: MybatisDemo